"""HTML and Markdown renderers for security reports."""

from __future__ import annotations

import html
from typing import Any


def escape_html(value: Any) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def _severity_label(value: str | None) -> str:
    text = str(value or "low")
    return text[:1].upper() + text[1:]


def _evidence_lines(finding: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    for item in finding.get("evidence_locations") or []:
        kind = item.get("kind") or "evidence"
        loc = item.get("location") or {}
        snippet = loc.get("snippet") or finding.get("snippet") or ""
        line = loc.get("line")
        label = str(kind).replace("_", " ").title()
        if snippet:
            where = f" (line {line})" if line is not None else ""
            lines.append(f"{label}{where}: {snippet}")
        else:
            lines.append(label)
    if not lines and finding.get("snippet"):
        lines.append(str(finding["snippet"]))
    return lines


def render_markdown_report(report: dict[str, Any]) -> str:
    summary = report.get("summary") or {}
    exec_summary = report.get("executive_summary") or {}
    lines: list[str] = [
        f"# Security Report: {report.get('project_name', 'project')}",
        "",
        "## Scan Summary",
        "",
        f"- **Project:** {report.get('project_name')}",
        f"- **Path:** `{report.get('project_path')}`",
        f"- **Scan date:** {report.get('scanned_at')}",
        f"- **Files scanned:** {report.get('files_scanned', 0)}",
        f"- **Scan duration:** {report.get('duration_seconds', 0)}s",
        f"- **Security score:** {report.get('security_score', 0)} / 100",
        f"- **Total findings:** {summary.get('total_findings', 0)}",
        f"- **High:** {summary.get('high', 0)}",
        f"- **Medium:** {summary.get('medium', 0)}",
        f"- **Low:** {summary.get('low', 0)}",
        "",
        "## Top Risk Categories",
        "",
    ]

    categories = report.get("top_risk_categories") or []
    if not categories:
        lines.append("_No risk categories — no findings._")
    else:
        lines.append("| Category | Count | Highest Severity |")
        lines.append("| --- | ---: | --- |")
        for item in categories:
            lines.append(
                f"| {item.get('display_name')} | {item.get('count')} | "
                f"{_severity_label(item.get('highest_severity'))} |"
            )

    lines.extend(
        [
            "",
            "## Executive Summary",
            "",
            "### Overall security posture",
            "",
            exec_summary.get("overall_posture", ""),
            "",
            "### Highest-risk vulnerability type",
            "",
            exec_summary.get("highest_risk_type", ""),
            "",
            "### Highest-priority files",
            "",
            exec_summary.get("highest_priority_files", ""),
            "",
            "### Recommended remediation order",
            "",
            exec_summary.get("recommended_remediation_order", ""),
            "",
        ]
    )

    ai_summary = report.get("ai_executive_summary")
    if ai_summary:
        lines.extend(
            [
                "## AI Executive Summary",
                "",
                "_AI-generated. Does not classify findings or override the deterministic engine._",
                "",
                ai_summary,
                "",
            ]
        )

    lines.extend(["## Findings", ""])
    findings = report.get("findings") or []
    if not findings:
        lines.append("_No findings detected._")
    else:
        for index, finding in enumerate(findings, start=1):
            lines.extend(_markdown_finding_card(index, finding))

    lines.extend(
        [
            "",
            "---",
            "",
            "_Generated by AI Security Assistant. Deterministic engine is the source of truth._",
            "",
        ]
    )
    return "\n".join(lines)


def _markdown_finding_card(index: int, finding: dict[str, Any]) -> list[str]:
    severity = _severity_label(finding.get("confidence"))
    file_ref = finding.get("file") or "unknown"
    line = finding.get("line")
    location = f"{file_ref}:{line}" if line is not None else file_ref
    card = [
        f"### {index}. {finding.get('display_name') or finding.get('issue_type')}",
        "",
        f"- **Issue type:** `{finding.get('issue_type')}`",
        f"- **Severity / Confidence:** {severity}",
        f"- **Location:** `{location}`",
        "",
        "**Evidence**",
        "",
    ]
    evidence = _evidence_lines(finding)
    if evidence:
        for item in evidence:
            card.append(f"- `{item}`")
    else:
        card.append("- _No evidence locations provided._")

    card.extend(
        [
            "",
            "**Why it was flagged**",
            "",
            finding.get("missing_control")
            or "Potential security issue indicated by the deterministic analyzer.",
            "",
            "**Impact**",
            "",
            finding.get("impact")
            or "Impact depends on whether untrusted callers can trigger this behavior.",
            "",
            "**Recommended remediation**",
            "",
        ]
    )
    recommendations = list(finding.get("recommendations") or [])
    if recommendations:
        for item in recommendations[:5]:
            card.append(f"- {item}")
    else:
        card.append("- Review and apply the safest available control for this finding.")

    suggestion = finding.get("ai_fix_suggestion")
    if isinstance(suggestion, dict) and suggestion.get("replacement_code"):
        card.extend(
            [
                "",
                "**AI Fix Suggestion**",
                "",
                "_AI-generated suggestion. Review before applying. Not guaranteed secure._",
                "",
                suggestion.get("summary") or "",
                "",
                "```python",
                str(suggestion.get("replacement_code")),
                "```",
                "",
                suggestion.get("explanation") or "",
                "",
            ]
        )

    card.append("")
    return card


def render_html_report(report: dict[str, Any]) -> str:
    summary = report.get("summary") or {}
    exec_summary = report.get("executive_summary") or {}
    categories = report.get("top_risk_categories") or []
    findings = report.get("findings") or []

    category_rows = "".join(
        f"<tr><td>{escape_html(item.get('display_name'))}</td>"
        f"<td>{escape_html(item.get('count'))}</td>"
        f"<td><span class='badge {escape_html(item.get('highest_severity'))}'>"
        f"{escape_html(_severity_label(item.get('highest_severity')))}</span></td></tr>"
        for item in categories
    ) or "<tr><td colspan='3'>No risk categories — no findings.</td></tr>"

    finding_cards = "".join(_html_finding_card(index, finding) for index, finding in enumerate(findings, start=1))
    if not finding_cards:
        finding_cards = "<p class='muted'>No findings detected.</p>"

    ai_block = ""
    if report.get("ai_executive_summary"):
        ai_block = f"""
        <section id="ai-summary">
          <h2>AI Executive Summary</h2>
          <p class="disclaimer">AI-generated. Does not classify findings or override the deterministic engine.</p>
          <p>{escape_html(report['ai_executive_summary'])}</p>
        </section>
        """

    nav_findings = "".join(
        f"<li><a href='#finding-{index}'>{escape_html(finding.get('display_name') or finding.get('issue_type'))}</a></li>"
        for index, finding in enumerate(findings, start=1)
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Security Report — {escape_html(report.get('project_name'))}</title>
  <style>
    :root {{
      --bg: #f6f7f9;
      --card: #ffffff;
      --text: #1f2933;
      --muted: #616e7c;
      --border: #d9e2ec;
      --high: #b91c1c;
      --medium: #b45309;
      --low: #1d4ed8;
      --accent: #0f766e;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
      color: var(--text);
      background: linear-gradient(180deg, #eef2f7 0%, var(--bg) 220px);
      line-height: 1.5;
    }}
    .wrap {{
      max-width: 980px;
      margin: 0 auto;
      padding: 2rem 1.25rem 3rem;
    }}
    header.hero {{
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 1.5rem;
      margin-bottom: 1.25rem;
    }}
    h1 {{ margin: 0 0 0.35rem; font-size: 1.8rem; }}
    h2 {{ margin: 0 0 0.75rem; font-size: 1.2rem; }}
    h3 {{ margin: 0 0 0.5rem; font-size: 1.05rem; }}
    .muted {{ color: var(--muted); }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
      gap: 0.75rem;
      margin: 1rem 0 0;
    }}
    .card {{
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 0.9rem 1rem;
    }}
    .card .label {{ font-size: 0.8rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.04em; }}
    .card .value {{ font-size: 1.35rem; font-weight: 700; margin-top: 0.2rem; }}
    .score {{ color: var(--accent); }}
    section {{
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 1.1rem 1.2rem;
      margin-top: 1rem;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
    }}
    th, td {{
      text-align: left;
      padding: 0.55rem 0.4rem;
      border-bottom: 1px solid var(--border);
      vertical-align: top;
    }}
    th {{ font-size: 0.85rem; color: var(--muted); }}
    .badge {{
      display: inline-block;
      padding: 0.1rem 0.45rem;
      border-radius: 999px;
      font-size: 0.8rem;
      font-weight: 600;
      color: #fff;
      background: #64748b;
    }}
    .badge.high {{ background: var(--high); }}
    .badge.medium {{ background: var(--medium); }}
    .badge.low {{ background: var(--low); }}
    .finding {{
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 1rem;
      margin-top: 0.85rem;
    }}
    pre {{
      background: #0b1220;
      color: #e2e8f0;
      padding: 0.75rem 0.9rem;
      border-radius: 8px;
      overflow-x: auto;
      white-space: pre-wrap;
      word-break: break-word;
      font-size: 0.9rem;
    }}
    nav ul {{ margin: 0.35rem 0 0; padding-left: 1.1rem; }}
    .disclaimer {{ font-style: italic; color: var(--muted); }}
    footer {{
      margin-top: 1.25rem;
      color: var(--muted);
      font-size: 0.9rem;
    }}
    @media (max-width: 640px) {{
      h1 {{ font-size: 1.45rem; }}
      .wrap {{ padding: 1rem 0.85rem 2rem; }}
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <header class="hero">
      <h1>Security Report</h1>
      <p class="muted">{escape_html(report.get('project_name'))} · {escape_html(report.get('scanned_at'))}</p>
      <div class="grid">
        <div class="card"><div class="label">Security Score</div><div class="value score">{escape_html(report.get('security_score'))}/100</div></div>
        <div class="card"><div class="label">Files Scanned</div><div class="value">{escape_html(report.get('files_scanned'))}</div></div>
        <div class="card"><div class="label">Total Findings</div><div class="value">{escape_html(summary.get('total_findings'))}</div></div>
        <div class="card"><div class="label">High</div><div class="value">{escape_html(summary.get('high'))}</div></div>
        <div class="card"><div class="label">Medium</div><div class="value">{escape_html(summary.get('medium'))}</div></div>
        <div class="card"><div class="label">Low</div><div class="value">{escape_html(summary.get('low'))}</div></div>
        <div class="card"><div class="label">Duration</div><div class="value">{escape_html(report.get('duration_seconds'))}s</div></div>
      </div>
    </header>

    <section id="summary">
      <h2>Scan Summary</h2>
      <p><strong>Path:</strong> <code>{escape_html(report.get('project_path'))}</code></p>
      <p><strong>Files failed:</strong> {escape_html(report.get('files_failed', 0))}</p>
    </section>

    <section id="categories">
      <h2>Top Risk Categories</h2>
      <table>
        <thead><tr><th>Category</th><th>Count</th><th>Highest Severity</th></tr></thead>
        <tbody>{category_rows}</tbody>
      </table>
    </section>

    <section id="executive">
      <h2>Executive Summary</h2>
      <h3>Overall security posture</h3>
      <p>{escape_html(exec_summary.get('overall_posture'))}</p>
      <h3>Highest-risk vulnerability type</h3>
      <p>{escape_html(exec_summary.get('highest_risk_type'))}</p>
      <h3>Highest-priority files</h3>
      <p>{escape_html(exec_summary.get('highest_priority_files'))}</p>
      <h3>Recommended remediation order</h3>
      <pre>{escape_html(exec_summary.get('recommended_remediation_order'))}</pre>
    </section>

    {ai_block}

    <section id="nav">
      <h2>Findings Navigation</h2>
      <nav><ul>{nav_findings or "<li class='muted'>No findings</li>"}</ul></nav>
    </section>

    <section id="findings">
      <h2>Findings</h2>
      {finding_cards}
    </section>

    <footer>Generated by AI Security Assistant. Deterministic engine is the source of truth.</footer>
  </div>
</body>
</html>
"""


def _html_finding_card(index: int, finding: dict[str, Any]) -> str:
    severity = str(finding.get("confidence") or "low")
    file_ref = finding.get("file") or "unknown"
    line = finding.get("line")
    location = f"{file_ref}:{line}" if line is not None else str(file_ref)
    evidence = _evidence_lines(finding)
    evidence_html = (
        "<ul>"
        + "".join(f"<li><code>{escape_html(item)}</code></li>" for item in evidence)
        + "</ul>"
        if evidence
        else "<p class='muted'>No evidence locations provided.</p>"
    )
    recommendations = list(finding.get("recommendations") or [])
    rec_html = (
        "<ul>"
        + "".join(f"<li>{escape_html(item)}</li>" for item in recommendations[:5])
        + "</ul>"
        if recommendations
        else "<p>Review and apply the safest available control for this finding.</p>"
    )

    suggestion = finding.get("ai_fix_suggestion")
    suggestion_html = ""
    if isinstance(suggestion, dict) and suggestion.get("replacement_code"):
        suggestion_html = f"""
        <div class="ai-fix">
          <h3>AI Fix Suggestion</h3>
          <p class="disclaimer">AI-generated suggestion. Review before applying. Not guaranteed secure.</p>
          <p>{escape_html(suggestion.get('summary'))}</p>
          <pre>{escape_html(suggestion.get('replacement_code'))}</pre>
          <p>{escape_html(suggestion.get('explanation'))}</p>
        </div>
        """

    return f"""
    <article class="finding" id="finding-{index}">
      <h3>{index}. {escape_html(finding.get('display_name') or finding.get('issue_type'))}
        <span class="badge {escape_html(severity)}">{escape_html(_severity_label(severity))}</span>
      </h3>
      <p><strong>Issue type:</strong> <code>{escape_html(finding.get('issue_type'))}</code></p>
      <p><strong>Location:</strong> <code>{escape_html(location)}</code></p>
      <h3>Evidence</h3>
      {evidence_html}
      <h3>Why it was flagged</h3>
      <p>{escape_html(finding.get('missing_control') or 'Potential security issue indicated by the deterministic analyzer.')}</p>
      <h3>Impact</h3>
      <p>{escape_html(finding.get('impact') or 'Impact depends on whether untrusted callers can trigger this behavior.')}</p>
      <h3>Recommended remediation</h3>
      {rec_html}
      {suggestion_html}
    </article>
    """
